# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x12\x63onnectrpc.chat.v1\"(\n\nSayRequest\x12\x1a\n\x08sentence\x18\x01 \x01(\tR\x08sentence\")\n\x0bSayResponse\x12\x1a\n\x08sentence\x18\x01 \x01(\tR\x08sentence2W\n\x0b\x43hatService\x12H\n\x03Say\x12\x1e.connectrpc.chat.v1.SayRequest\x1a\x1f.connectrpc.chat.v1.SayResponse\"\x00\x42\x8d\x01\n\x16\x63om.connectrpc.chat.v1B\tChatProtoP\x01\xa2\x02\x03\x43\x43X\xaa\x02\x12\x43onnectrpc.Chat.V1\xca\x02\x12\x43onnectrpc\\Chat\\V1\xe2\x02\x1e\x43onnectrpc\\Chat\\V1\\GPBMetadata\xea\x02\x14\x43onnectrpc::Chat::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.connectrpc.chat.v1B\tChatProtoP\001\242\002\003CCX\252\002\022Connectrpc.Chat.V1\312\002\022Connectrpc\\Chat\\V1\342\002\036Connectrpc\\Chat\\V1\\GPBMetadata\352\002\024Connectrpc::Chat::V1'
  _globals['_SAYREQUEST']._serialized_start=34
  _globals['_SAYREQUEST']._serialized_end=74
  _globals['_SAYRESPONSE']._serialized_start=76
  _globals['_SAYRESPONSE']._serialized_end=117
  _globals['_CHATSERVICE']._serialized_start=119
  _globals['_CHATSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
